# Generated by Django 3.2.8 on 2021-12-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='archive',
            new_name='archived',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='mute',
            new_name='muted',
        ),
    ]
