# Generated by Django 3.1.5 on 2021-02-08 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210201_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='message',
            field=models.TextField(blank=True, default=False, max_length=10000, null=True),
        ),
    ]
