# Generated by Django 3.1.5 on 2021-02-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210208_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Log',
            new_name='Newt',
        ),
    ]
