# Generated by Django 3.1.5 on 2021-02-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course_coursecodeformat_emailsubstring_idformat_institution_log_sessiontype_user_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='country',
            field=models.CharField(default='UK', max_length=128),
            preserve_default=False,
        ),
    ]
