# Generated by Django 3.1.5 on 2021-02-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_institution_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertype',
            old_name='desceription',
            new_name='description',
        ),
    ]
