# Generated by Django 3.2.8 on 2021-12-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'institution')},
        ),
    ]
